//! Stable, browser-safe quantities and identifiers shared across wire contracts.
//! Constructors and both JSON and SCALE decoding preserve quantity invariants.
#![allow(clippy::missing_errors_doc)]

use chrono::{Datelike, NaiveDate, Weekday};
use parity_scale_codec::{Decode, Encode, Input};
use serde::{Deserialize, Serialize};
use std::{fmt, str::FromStr};

/// Invalid wire value or checked arithmetic failure.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum ValidationError {
    /// A hexadecimal identifier has an invalid length or character.
    #[error("invalid hexadecimal identifier")]
    InvalidHex,
    /// An integer exceeds its permitted range.
    #[error("{0} is outside its permitted range")]
    OutOfRange(&'static str),
    /// An amount is not a canonical unsigned decimal string.
    #[error("invalid unsigned decimal amount")]
    InvalidAmount,
    /// Arithmetic cannot be represented by the quantity.
    #[error("arithmetic overflow or underflow")]
    Arithmetic,
    /// A weekly range ends before it starts.
    #[error("week window ends before it starts")]
    ReversedWindow,
}

fn parse_hex<const N: usize>(value: &str) -> Result<[u8; N], ValidationError> {
    let value = value.strip_prefix("0x").unwrap_or(value);
    if value.len() != N * 2 || !value.is_ascii() {
        return Err(ValidationError::InvalidHex);
    }
    let mut bytes = [0; N];
    for (slot, pair) in bytes.iter_mut().zip(value.as_bytes().chunks_exact(2)) {
        let high = char::from(pair[0])
            .to_digit(16)
            .ok_or(ValidationError::InvalidHex)?;
        let low = char::from(pair[1])
            .to_digit(16)
            .ok_or(ValidationError::InvalidHex)?;
        *slot = u8::try_from(high * 16 + low).map_err(|_| ValidationError::InvalidHex)?;
    }
    Ok(bytes)
}

macro_rules! hex_type {
    ($name:ident, $size:expr, $doc:literal) => {
        #[doc = $doc]
        #[derive(
            Clone,
            Copy,
            PartialEq,
            Eq,
            PartialOrd,
            Ord,
            Hash,
            Encode,
            Decode,
            Serialize,
            Deserialize,
        )]
        #[serde(try_from = "String", into = "String")]
        pub struct $name([u8; $size]);
        impl $name {
            /// Construct from fixed-width bytes generated by the owning service.
            #[must_use]
            pub const fn from_bytes(bytes: [u8; $size]) -> Self {
                Self(bytes)
            }
            /// Borrow the canonical byte representation.
            #[must_use]
            pub const fn as_bytes(&self) -> &[u8; $size] {
                &self.0
            }
            /// Extract the canonical byte representation.
            #[must_use]
            pub const fn into_bytes(self) -> [u8; $size] {
                self.0
            }
        }
        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str("0x")?;
                for byte in self.0 {
                    write!(f, "{byte:02x}")?;
                }
                Ok(())
            }
        }
        impl fmt::Debug for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                fmt::Display::fmt(self, f)
            }
        }
        impl FromStr for $name {
            type Err = ValidationError;
            fn from_str(value: &str) -> Result<Self, Self::Err> {
                parse_hex(value).map(Self)
            }
        }
        impl TryFrom<String> for $name {
            type Error = ValidationError;
            fn try_from(value: String) -> Result<Self, Self::Error> {
                value.parse()
            }
        }
        impl From<$name> for String {
            fn from(value: $name) -> Self {
                value.to_string()
            }
        }
    };
}

hex_type!(
    AccountId32,
    32,
    "An sr25519 public account; JSON is 0x-prefixed hexadecimal."
);
hex_type!(
    EntityId,
    16,
    "An opaque provider-generated contract or entity identifier."
);
hex_type!(
    OperationId,
    16,
    "An immutable idempotency identity for one provider operation."
);
hex_type!(
    PrincipalId,
    16,
    "An adapter-owned classic authentication identity."
);
hex_type!(
    WalletId,
    16,
    "A custody-owned wallet identifier, never a key."
);
hex_type!(
    ProviderInstanceId,
    16,
    "A provider-state generation; changes when disposable state resets."
);
hex_type!(
    PayloadHash,
    32,
    "SHA-256 of exact SCALE signable bytes, computed outside this crate."
);
hex_type!(
    Sr25519Signature,
    64,
    "A fixed-width sr25519 signature; no secret material."
);

/// Non-negative integer KVN token units; JSON is always a decimal string.
#[derive(
    Debug,
    Default,
    Clone,
    Copy,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Encode,
    Decode,
    Serialize,
    Deserialize,
)]
#[serde(try_from = "String", into = "String")]
pub struct Money(u64);
impl Money {
    /// No units.
    pub const ZERO: Self = Self(0);
    /// Construct integer token units without assigning a decimal display scale.
    #[must_use]
    pub const fn new(units: u64) -> Self {
        Self(units)
    }
    /// Return integer token units.
    #[must_use]
    pub const fn units(self) -> u64 {
        self.0
    }
    /// Add amounts without wrapping.
    pub fn checked_add(self, other: Self) -> Result<Self, ValidationError> {
        self.0
            .checked_add(other.0)
            .map(Self)
            .ok_or(ValidationError::Arithmetic)
    }
    /// Subtract without creating a negative balance.
    pub fn checked_sub(self, other: Self) -> Result<Self, ValidationError> {
        self.0
            .checked_sub(other.0)
            .map(Self)
            .ok_or(ValidationError::Arithmetic)
    }
}
impl TryFrom<String> for Money {
    type Error = ValidationError;
    fn try_from(value: String) -> Result<Self, Self::Error> {
        if value.is_empty()
            || !value.bytes().all(|b| b.is_ascii_digit())
            || (value.len() > 1 && value.starts_with('0'))
        {
            return Err(ValidationError::InvalidAmount);
        }
        value
            .parse()
            .map(Self)
            .map_err(|_| ValidationError::InvalidAmount)
    }
}
impl From<Money> for String {
    fn from(value: Money) -> Self {
        value.0.to_string()
    }
}
impl fmt::Display for Money {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

macro_rules! unsigned_quantity {
    ($name:ident, $repr:ty, $doc:literal) => {
        #[doc = $doc]
        #[derive(
            Debug,
            Default,
            Clone,
            Copy,
            PartialEq,
            Eq,
            PartialOrd,
            Ord,
            Hash,
            Encode,
            Decode,
            Serialize,
            Deserialize,
        )]
        #[serde(transparent)]
        pub struct $name($repr);
        impl $name {
            /// Zero quantity.
            pub const ZERO: Self = Self(0);
            /// Construct from a non-negative integer.
            #[must_use]
            pub const fn new(value: $repr) -> Self {
                Self(value)
            }
            /// Return the underlying integer.
            #[must_use]
            pub const fn get(self) -> $repr {
                self.0
            }
            /// Add without wrapping.
            pub fn checked_add(self, other: Self) -> Result<Self, ValidationError> {
                self.0
                    .checked_add(other.0)
                    .map(Self)
                    .ok_or(ValidationError::Arithmetic)
            }
            /// Subtract without creating a negative quantity.
            pub fn checked_sub(self, other: Self) -> Result<Self, ValidationError> {
                self.0
                    .checked_sub(other.0)
                    .map(Self)
                    .ok_or(ValidationError::Arithmetic)
            }
        }
    };
}
unsigned_quantity!(
    Minutes,
    u32,
    "An integer duration or capacity in minutes, never floating-point hours."
);
unsigned_quantity!(UnixSeconds, u64, "A UTC Unix timestamp in whole seconds.");

macro_rules! bounded_quantity {
    ($name:ident, $max:expr, $doc:literal) => {
        #[doc = $doc]
        #[derive(
            Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Encode, Serialize, Deserialize,
        )]
        #[serde(try_from = "u8", into = "u8")]
        pub struct $name(u8);
        impl $name {
            /// Validate and construct the quantity.
            pub fn new(value: u8) -> Result<Self, ValidationError> {
                if value <= $max {
                    Ok(Self(value))
                } else {
                    Err(ValidationError::OutOfRange(stringify!($name)))
                }
            }
            /// Return the validated integer.
            #[must_use]
            pub const fn get(self) -> u8 {
                self.0
            }
        }
        impl TryFrom<u8> for $name {
            type Error = ValidationError;
            fn try_from(value: u8) -> Result<Self, Self::Error> {
                Self::new(value)
            }
        }
        impl From<$name> for u8 {
            fn from(value: $name) -> Self {
                value.0
            }
        }
        impl Decode for $name {
            fn decode<I: Input>(input: &mut I) -> Result<Self, parity_scale_codec::Error> {
                Self::new(u8::decode(input)?).map_err(|_| "quantity outside range".into())
            }
        }
    };
}
bounded_quantity!(
    Percentage,
    100,
    "An integer percentage between zero and one hundred."
);
bounded_quantity!(
    Score,
    10,
    "An individual rating between zero and ten, inclusive."
);

/// A validated ISO week-year and week number, ordered chronologically.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Encode, Serialize, Deserialize,
)]
#[serde(try_from = "WeekWire", into = "WeekWire")]
pub struct Week {
    iso_year: i32,
    week: u8,
}
#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct WeekWire {
    iso_year: i32,
    week: u8,
}
impl Week {
    /// Validate the ISO calendar week, including week 53.
    pub fn new(iso_year: i32, week: u8) -> Result<Self, ValidationError> {
        NaiveDate::from_isoywd_opt(iso_year, u32::from(week), Weekday::Mon)
            .ok_or(ValidationError::OutOfRange("ISO week"))?;
        Ok(Self { iso_year, week })
    }
    /// ISO week-year, which may differ from a date's calendar year.
    #[must_use]
    pub const fn iso_year(self) -> i32 {
        self.iso_year
    }
    /// ISO week number, from 1 to 52 or 53.
    #[must_use]
    pub const fn week(self) -> u8 {
        self.week
    }
    /// The next ISO week, including year boundaries.
    pub fn next(self) -> Result<Self, ValidationError> {
        let day = NaiveDate::from_isoywd_opt(self.iso_year, u32::from(self.week), Weekday::Mon)
            .and_then(|d| d.checked_add_signed(chrono::Duration::weeks(1)))
            .ok_or(ValidationError::OutOfRange("ISO week"))?;
        let iso = day.iso_week();
        Self::new(
            iso.year(),
            u8::try_from(iso.week()).map_err(|_| ValidationError::Arithmetic)?,
        )
    }
}
impl TryFrom<WeekWire> for Week {
    type Error = ValidationError;
    fn try_from(value: WeekWire) -> Result<Self, Self::Error> {
        Self::new(value.iso_year, value.week)
    }
}
impl From<Week> for WeekWire {
    fn from(value: Week) -> Self {
        Self {
            iso_year: value.iso_year,
            week: value.week,
        }
    }
}
impl Decode for Week {
    fn decode<I: Input>(input: &mut I) -> Result<Self, parity_scale_codec::Error> {
        Self::new(i32::decode(input)?, u8::decode(input)?).map_err(|_| "invalid ISO week".into())
    }
}

/// Inclusive scheduling range; allocation never extends beyond its end.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Encode, Serialize, Deserialize)]
#[serde(try_from = "WeekWindowWire", into = "WeekWindowWire")]
pub struct WeekWindow {
    start: Week,
    end: Week,
}
#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct WeekWindowWire {
    start: Week,
    end: Week,
}
impl WeekWindow {
    /// Construct an inclusive, chronologically ordered window.
    pub fn new(start: Week, end: Week) -> Result<Self, ValidationError> {
        if start > end {
            return Err(ValidationError::ReversedWindow);
        }
        Ok(Self { start, end })
    }
    /// First included week.
    #[must_use]
    pub const fn start(self) -> Week {
        self.start
    }
    /// Last included week.
    #[must_use]
    pub const fn end(self) -> Week {
        self.end
    }
    /// Test whether a week belongs to this window.
    #[must_use]
    pub fn contains(self, week: Week) -> bool {
        self.start <= week && week <= self.end
    }
}
impl TryFrom<WeekWindowWire> for WeekWindow {
    type Error = ValidationError;
    fn try_from(value: WeekWindowWire) -> Result<Self, Self::Error> {
        Self::new(value.start, value.end)
    }
}
impl From<WeekWindow> for WeekWindowWire {
    fn from(value: WeekWindow) -> Self {
        Self {
            start: value.start,
            end: value.end,
        }
    }
}
impl Decode for WeekWindow {
    fn decode<I: Input>(input: &mut I) -> Result<Self, parity_scale_codec::Error> {
        Self::new(Week::decode(input)?, Week::decode(input)?)
            .map_err(|_| "reversed week window".into())
    }
}

/// Decimal-string serde support for exact reputation accumulators in read DTOs.
pub mod decimal_u128 {
    use serde::{Deserialize, Deserializer, Serializer, de::Error};
    /// Serialize an integer without JavaScript precision loss.
    pub fn serialize<S: Serializer>(value: &u128, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&value.to_string())
    }
    /// Read a non-negative decimal integer string.
    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<u128, D::Error> {
        let value = String::deserialize(deserializer)?;
        if value.is_empty() || !value.bytes().all(|b| b.is_ascii_digit()) {
            return Err(D::Error::custom("invalid decimal integer"));
        }
        value.parse().map_err(D::Error::custom)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn identifiers_roundtrip_and_reject_bad_input() -> Result<(), Box<dyn std::error::Error>> {
        let account = AccountId32::from_bytes([42; 32]);
        assert_eq!(
            account,
            serde_json::from_str(&serde_json::to_string(&account)?)?
        );
        assert!("0xff".parse::<AccountId32>().is_err());
        assert!("g".repeat(64).parse::<AccountId32>().is_err());
        assert!(serde_json::from_str::<Sr25519Signature>("\"0xff\"").is_err());
        Ok(())
    }
    #[test]
    fn quantities_validate_json_scale_and_overflow() -> Result<(), Box<dyn std::error::Error>> {
        assert_eq!(
            serde_json::to_string(&Money::new(u64::MAX))?,
            format!("\"{}\"", u64::MAX)
        );
        for bad in [
            "1",
            "\"-1\"",
            "\"1.5\"",
            "\"01\"",
            "\"18446744073709551616\"",
        ] {
            assert!(serde_json::from_str::<Money>(bad).is_err());
        }
        assert!(Money::new(u64::MAX).checked_add(Money::new(1)).is_err());
        assert!(Money::ZERO.checked_sub(Money::new(1)).is_err());
        assert!(serde_json::from_str::<Score>("11").is_err());
        assert!(Score::decode(&mut &[11_u8][..]).is_err());
        assert!(Percentage::decode(&mut &[101_u8][..]).is_err());
        assert!(serde_json::from_str::<Minutes>("-1").is_err());
        Ok(())
    }
    #[test]
    fn iso_weeks_and_windows_cannot_be_forged() -> Result<(), Box<dyn std::error::Error>> {
        assert_eq!(Week::new(2020, 53)?.next()?, Week::new(2021, 1)?);
        assert!(Week::new(2021, 53).is_err());
        assert!(serde_json::from_str::<Week>(r#"{"isoYear":2021,"week":53}"#).is_err());
        assert!(Week::decode(&mut &(2021_i32, 53_u8).encode()[..]).is_err());
        let start = Week::new(2026, 20)?;
        let end = Week::new(2026, 19)?;
        assert!(WeekWindow::new(start, end).is_err());
        assert!(WeekWindow::decode(&mut &(start, end).encode()[..]).is_err());
        Ok(())
    }
}
