[package]
name = "generated-contracts"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
domain-primitives.workspace = true
serde.workspace = true
thiserror.workspace = true
parity-scale-codec.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
