[package]
name = "leptos-web"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
domain-primitives.workspace = true
generated-contracts.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
leptos.workspace = true
gloo-net.workspace = true
wasm-bindgen = "0.2.128"
js-sys = "0.3.105"
web-sys = { version = "0.3.105", features = ["AbortController", "AbortSignal", "Crypto", "EventSource", "EventSourceInit", "FormData", "HtmlFormElement", "MessageEvent", "RequestCredentials", "Window"] }

[lints]
workspace = true
